name: FactoryLife
version: 0.1.3
author: Eden
main: com.gmail.edenthink.FactoryLife
softdepend: [vault]
commands:
   order:
   ticket:
   aeitems:
   saveinv:
permissions:
   FactoryLife.ae:
      default: false