name: FactoryLife
version: 0.1
author: Eden
main: com.gmail.edenthink.FactoryLife
softdepend: [vault]
command:
  order:
    description: Go for your order
    usage: /order info\n /order one|two|three